docs_dir: docs/book
site_dir: docs/html
extra:
  project: Packages
  current_version: v4
  versions:
    - v4
    - v3
nav:
  - Home: index.md
  - v4:
      - Overview: v4/overview.md
      - Installation: v4/installation.md
      - Configuration: v4/configuration.md
      - "Updating the Pipeline": v4/updating-pipeline.md
  - v3:
      - Installation: v3/installation.md
      - Configuration: v3/configuration.md
      - "Updating the Pipeline": v3/updating-pipeline.md
site_name: dot-rbac-guard
site_description: "The rbac authorization guards service authorizes users for accessing certain parts of an application based on various criteria"
repo_url: "https://github.com/dotkernel/dot-rbac-guard"
plugins:
  - search
